name: Setup Node.js
description: Wrapper for actions/setup-node@v4

inputs:
  node-version:
    required: false
    default: "22"
    description: Node.js version to use
  registry-url:
    required: false
    default: ""
    description: NPM registry URL
  cache:
    required: false
    default: "pnpm"
    description: Cache dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      id: setup-node
      name: Install Node.js
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: ${{ inputs.cache }}
