name: PNPM repo
description: PNPM repo wrapper

inputs:
  version:
    required: false
    default: "10"
    description: PNPM version
  run_install:
    required: false
    default: "false"
    description: Run pnpm install

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      id: pnpm
      name: Install pnpm
      with:
        version: ${{ inputs.version }}
        run_install: ${{ inputs.run_install }}
