name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout

      - name: Setup Node
        uses: ./.github/actions/node-pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run Build
        run: pnpm build
