name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/node-pnpm

      - name: Run Lint
        run: pnpm lint

      - name: Run Build
        run: pnpm build
